name: lando-solr-6
services:
  defaults:
    type: solr:6
    portforward: true
    config:
      dir: '6.x-conf'
  helper:
    type: php
    via: cli
tooling:
  post-record-defaults:
    cmd: "curl http://defaults:8983/solr/lando/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/solr": ./../../