name: lando-solr-3
services:
  legacy3:
    portforward: true
    type: solr:3
    config:
      dir: '3.x-conf'
  helper:
    type: php
    via: cli
# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/solr": ./../../