name: lando-solr-4
services:
  legacy4:
    portforward: true
    type: solr:4
    config:
      dir: '4.x-conf'
  helper:
    type: php
    via: cli
tooling:
  post-record-legacy:
    cmd: "curl http://legacy4:8983/solr/collection1/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: legacy4

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/solr": ./../../