name: lando-solr-8
services:
  defaults:
    type: solr:8
    portforward: true
    config:
      dir: '8.x-conf'
  patch:
    type: solr:8.6
    core: solo
    portforward: true
    config:
      dir: '8.x-conf'
  helper:
    type: php
    via: cli
tooling:
  post-record-defaults:
    cmd: "curl http://defaults:8983/solr/lando/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: defaults
  post-record-patch:
    cmd: "curl http://patch:8983/solr/solo/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: patch

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/solr": ./../../