name: lando-solr-7
services:
  defaults:
    type: solr
  custom:
    type: solr:7.7
    core: freedom
    portforward: true
    config:
      dir: '7.x-conf'
  helper:
    type: php
    via: cli
tooling:
  post-record-custom:
    cmd: "curl http://custom:8983/solr/freedom/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: custom
  post-record-defaults:
    cmd: "curl http://defaults:8983/solr/lando/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: defaults

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/solr": ./../../